name: Udyami Project 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Set up Chrome for Selenium
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # Step 4: Verify Chrome installation
      - name: Verify Chrome installation
        run: google-chrome --version

      # Step 5: Install ChromeDriver
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Step 6: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 7: Run Tests
      - name: Run Cucumber/Selenium Tests
        run: mvn test

      # Step 8: Upload test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
