name: Udyami Project 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest  # Windows runner

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      # Step 3: Verify Chrome installation
      - name: Verify Chrome installation
        run: |
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version


      # Step 4: Build with Maven (skip tests first)
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 5: Run Selenium/Cucumber Tests (headless mode)
      - name: Run Cucumber/Selenium Tests
        run: mvn test -Dheadless=true

      # Step 6: Upload test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
